<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>All</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b487c733-5f55-44c7-9699-0f9bcd956016</testSuiteGuid>
   <testCaseLink>
      <guid>89eaf223-130a-4d7a-bfd4-91428fd7c838</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/header and footer Desktop/Footer Categories Desktop</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ecfcf0ef-0796-4ff9-a267-fc0c9f6576c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/header and footer Desktop/Footer Follow us Desktop</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb7ebe99-e3db-4cc5-8a43-279bea401d1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c757002a-6717-4fa6-b4d0-8de8d932daeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8b6c8fd-3bad-4675-86d1-4af9d169546a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc721027-076a-4f8c-97ad-a64d71af1501</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7ca34b3-cfa2-4b37-9dad-21fbad9f3a7c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/header and footer Desktop/Footer Information Desktop</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ed1712f-b793-4f05-8d98-f949a6928b95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1c9aa8a-19ce-466b-a18b-7cc2cda5b7ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b63e001e-cce1-49b1-bb09-4fff9e556590</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b310e970-1ae1-40d1-a8b0-809ee80beb7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec3ce030-786b-4e30-ad46-cb415517f8ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b43c7e75-56db-401c-965d-f82e28a6c7d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c63f8dcb-da58-4413-942f-099b3a47c691</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4755e61d-0d8c-4a4c-8640-8fbd518164e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6f1c3a0-7608-4fe5-9fd7-04d8ed57623f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/header and footer Desktop/Footer My account Desktop</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09f5ed75-b9b3-4aeb-9419-f3e5470688a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>359b0056-f1ad-4dbb-942b-a86bf9cd7d14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80bb8324-c984-46bb-ace6-31d0a8f8a4dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b0c456c-3991-48b9-8693-2e7f2693d2ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1921b353-78e5-4a04-aea6-6d067c502032</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>438a3676-51fd-4aad-8110-a7734cd4b1a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/header and footer Desktop/Footer Store information Desktop</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c97622b5-ea4c-4916-b504-54b730ecba6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/header and footer Desktop/Footer Subscribe Desktop</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d56d74b2-abd2-4004-baf5-45cea5f887e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/header and footer Desktop/Header Search Desktop</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d79db66f-f755-4a82-9d98-cc9d4706641a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/header and footer Desktop/Header-Elements Present Desktop</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>67df5b82-2e81-4aa3-9098-d8cec5565398</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/Navigation/Main Navigation Menu Desktop</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>323f1d1f-9f46-4d5b-aded-8a4490fcc0af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/Navigation/Main Navigation Sub Menu -Dresses- Desktop</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c60049cb-ad2e-4594-a92b-592abb542abe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/Navigation/Main Navigation Sub Menu -Women- Desktop</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7d962613-b9cd-47e2-8ffd-c985cb43b590</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/regression/User andComercial workflows/Sign in and Sign out Desktop</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
